# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        files: \.(yaml|yml)$|^\.clangd$
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v21.1.1'  # Use the sha / tag you want to point at
    hooks:
    -   id: clang-format
-   repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
    -   id: black
